# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fa6a3b95a40337eaccd7b9d7bafb3f2cb220df594ae7d5987cdd5bccd99ef461083b9e2a5df048b6ee937b31f3ef1e3c70795d1c9145199e2b0b7ca1981ab05

test:
  secret_key_base: f910141b36647dc3f331f961e0172154f236d09b973a4e4cc4471ac84140f2d17f083f4f19971b14021cbc05f78e0d9856c93bc082b4a6f94ec46036a70d161c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
